---
- name: Install Grafana
  yum:
    name: grafana
    state: present

- name: Create Grafana user
  user:
    name: grafana
    shell: /bin/false
    createhome: true

- name: Create Grafana repository
  template:
    src: grafana.repo.j2
    dest: /etc/yum.repos.d/grafana.repo
  notify: Reload systemd

# - name: Configure Grafana
#   template:
#     src: grafana.ini.j2
#     dest: /etc/grafana/grafana.ini
#   notify: Restart Grafana

- name: Enable Grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes
